 
- title: 24-hour Individualized Care
  description: Experience personalized attention and assistance tailored to your unique needs for a comfortable stay
  img: visits
  alt: Elderly lady and middle aged caregiver smiling, talking and holding hands

- title: Dining
  description: Indulge in the joy of wholesome, home-cooked meals and delightful snacks, carefully crafted to nourish both your body and soul
  img: honey
  alt: Multigrain bread with honey swirled on it

- title: Housekeeping
  description: Relax and enjoy a clean and inviting living environment with our dedicated housekeeping services, allowing you to focus on what matters most
  img: cleaning1
  alt: Woman caregiver cleaning

- title: Medication Assistance
  description: Be at ease with our medication assistance, providing the support you need to manage your health effectively and safely
  img: pills
  alt: Caregiver handing bills to elderly client, while only hands are being shown

- title: Laundry
  description: Say goodbye to laundry worries! Let us handle the chores, ensuring your clothing and linens are always fresh and cared for
  img: laundry
  alt: Person pressing the on button for a laundry machine

- title: Dressing & Grooming Assistance
  description: Feel confident and well-groomed with our dedicated assistance in dressing and grooming, tailored to your individual preferences and needs
  img: grooming
  alt: Younger woman caregiver brushing the hair of an elderly woman sitting in a comfy chair

- title: Activities & Engagement
  description: Engage in a variety of recreational and wellness activities designed to promote physical, mental, and social well-being, fostering a vibrant and fulfilling lifestyle for residents
  img: activities
  alt: Elderly person doing activities like coloring

- title: Transportation Coordination
  description: Experience convenience at your fingertips with our transportation coordination, organizing access to essential services and activities beyond our facility
  img: transporation
  alt: Smiling caregiver putting seatbelt on senior client who is sitting in the front seat of a car

- title: Hospice Support
  description: During challenging times, our compassionate hospice support is here to provide comfort, dignity, and specialized care for you and your loved ones
  img: hospice1
  alt: someone touching an elderly person's shoulder, while they're resting under a beatiful sunset

- title: Care & Support
  description: Our dedicated staff is trained to offer personalized care, engaging activities, and a secure environment, ensuring the well-being and dignity of residents with memory challenges
  img: caresupport
  alt: Senior woman smiling at loving woman caregiver who is providing care and support

- title: Respite Care
  description: Enjoy short-term stays for temporary care, providing relief to family caregivers.
  img: respite-care
  alt: Smiling woman caregiver sitting next to and looking at happy senior woman on a couch

- title: Counseling and Support Services
  description: Benefit from the coordination of counseling services for emotional and psychological support, both for residents and their families
  img: counseling
  alt: Counselor listening to happy elderly person who is sitting on a couch